---
# This Playbook configure firewall 'ferm'
- name: Install requirements
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "{{ item }}"
    state: present
  with_items:
    - ferm
    - iptables

# https://github.com/ansible/ansible-modules-core/issues/593
# msg: no service or tool found for: firewalld
- name: Ferm | Disable other iptable frontends
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ disable_other_firewalls }}"
  ignore_errors: True

- name: Ferm | Display rules var
  debug:
    var: ferm_rules
    verbosity: 1

- name: Ferm | Make sure the directory for firewall rules exist
  file:
    path: /etc/ferm
    state: directory
    owner: root
    group: root

- name: Ferm | Create config directory for non-RedHat
  file:
    path: /etc/ferm.d
    state: directory
    owner: root
    group: root
  when: ansible_os_family != "RedHat"

- name: Ferm | Create config directory for RedHat
  file:
    path: /etc/ferm/ferm.d
    state: directory
    owner: root
    group: root
  when: ansible_os_family == "RedHat"

- name: Ferm | Include ferm.d directory on non-RedHat
  lineinfile:
    dest: /etc/ferm/ferm.conf
    line: '@include "/etc/ferm.d/";'
    regexp: '^\@include'
    backup: yes
    insertbefore: BOF
    create: yes
  check_mode: no
  when: ansible_os_family != "RedHat"

- name: Ferm | Include ferm.d directory on RedHat
  lineinfile:
    dest: /etc/ferm.conf
    line: '@include "/etc/ferm/ferm.d/";'
    regexp: '^\@include'
    backup: yes
    insertbefore: BOF
    create: yes
  check_mode: no
  when: ansible_os_family == "RedHat"

- name: Find ferm backup files on RedHat
  find:
    paths:      "/etc/ferm/ferm.d/"
    patterns:   "*~,*.bak"
  register: ferm_backup_files
  when: ansible_os_family == "RedHat"

- name: Remove the found ferm backup files on RedHat
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ ferm_backup_files.files }}"
  when: ansible_os_family == "RedHat"

- name: Find ferm backup files on non-RedHat
  find:
    paths:      "/etc/ferm.d/,/etc/ferm/ferm.d/"
    patterns:   "*~,*.bak"
  register: ferm_backup_files_non-redhat
  when: ansible_os_family != "RedHat"

- name: Remove the found ferm backup files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ ferm_backup_files_non-redhat.files }}"
  when: ansible_os_family != "RedHat"

- name: Ferm | Create the default ferm conf files on non-RedHat
  template:
    src: ferm.conf.j2
    dest: "/etc/ferm.d/{{item.key}}.conf"
    mode: 0655
    owner: root
    group: root
    backup: no
  with_dict: "{{ ferm_rules }}"
  notify:
    - reload ferm
  when: ansible_os_family != "RedHat"

- name: Ferm | Create the default ferm conf files on RedHat
  template:
    src: ferm.conf.j2
    dest: "/etc/ferm/ferm.d/{{item.key}}.conf"
    mode: 0655
    owner: root
    group: root
    backup: no
  with_dict: "{{ ferm_rules }}"
  notify:
    - reload ferm
  when: ansible_os_family == "RedHat"

- name: Ferm | Create extra ferm conf files on non-RedHat
  template:
    src: ferm.conf.j2
    dest: "/etc/ferm.d/{{item.key}}.conf"
    mode: 0655
    owner: root
    group: root
    backup: no
  with_dict: "{{ ferm_rules_extra | default({}) }}"
  notify:
    - reload ferm
  when: ansible_os_family != "RedHat" and ferm_rules_extra is defined

- name: Ferm | Create extra ferm conf files on RedHat
  template:
    src: ferm.conf.j2
    dest: "/etc/ferm/ferm.d/{{item.key}}.conf"
    mode: 0655
    owner: root
    group: root
    backup: no
  with_dict: "{{ ferm_rules_extra | default({}) }}"
  notify:
    - reload ferm
  when: ansible_os_family == "RedHat" and ferm_rules_extra

- name: Flush handlers
  meta: flush_handlers

- name: Ferm | Reload ferm
  service:
    name: ferm
    state: restarted
  changed_when: False
  register: fermreloaded

- name: Ferm | Enable ferm on boot
  service:
    name: ferm
    enabled: yes

- name: Ferm | If ferm_fail2ban is True - restart fail2ban as well if ferm is reloaded
  service:
    name: fail2ban
    state: restarted
  when: fermreloaded.changed and ferm_fail2ban
